src/Entity/Conge.php
<?php

namespace App\Entity;

use App\Repository\CongeRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\User;

#[ORM\Entity(repositoryClass: CongeRepository::class)]
class Conge
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $type = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $statut = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

       #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }


    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
}

src/Controller/CongeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\CongeRepository;
use App\Entity\Conge;

class CongeController extends AbstractController
{
    private $congeRepository;

    public function __construct(CongeRepository $congeRepository)
    {
        $this->congeRepository = $congeRepository;
    }

    #[Route('/conge', name: 'conge')]
    public function index(): Response
    {
        // Utiliser la méthode findAll() pour récupérer tous les congés
        $userConges = $this->congeRepository->findAll();

        // Passer les congés à la vue
        return $this->render('conge/index.html.twig', [
            'userConges' => $userConges,
        ]);
    }
   
}

src/Controller/HomeController.php
<?php
// src/Controller/HomeController.php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
}

src/Controller/StatsController.php
<?php

namespace App\Controller;

use App\Repository\UserRepository;
use App\Repository\CongeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;

class StatsController extends AbstractController
{
    private $congeRepository;
    private $userRepository;

    public function __construct(CongeRepository $congeRepository, UserRepository $userRepository)
    {
        $this->congeRepository = $congeRepository;
        $this->userRepository = $userRepository;
    }

    #[Route('/stats', name: 'app_stats')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        // Récupérer le nombre total de congés
        $totalConges = $this->congeRepository->count([]);
        $congesParType = $this->congeRepository->createQueryBuilder('c')
            ->select('c.type, COUNT(c.id) as count')
            ->groupBy('c.type')
            ->getQuery()
            ->getResult();

        // Requête SQL pour récupérer le nombre total de congés par type
        $connection = $entityManager->getConnection();
        $sql = 'SELECT c.type, COUNT(c.id) as count 
                FROM conge c 
                GROUP BY c.type';
        $stmt = $connection->prepare($sql);
        $congesParTypeSQL = $stmt->executeQuery()->fetchAllAssociative();

        return $this->render('stats/index.html.twig', [
            'totalConges' => $totalConges,
            'congesParType' => $congesParType,
            'congesParTypeSQL' => $congesParTypeSQL,
        ]);
    }

    #[Route('/stats/user', name: 'app_stats_user')]
    public function statsParUtilisateur(EntityManagerInterface $entityManager): Response
    {
        // Requête DQL pour compter les congés par utilisateur
        $startTimeDQL = microtime(true);
        $congesParUser = $this->congeRepository->createQueryBuilder('c')
            ->select('u.nom, u.prenom, COUNT(c.id) as count')
            ->join('c.user', 'u')
            ->groupBy('u.id')
            ->getQuery()
            ->getResult();
        $endTimeDQL = microtime(true);
        $executionTimeDQL = round(($endTimeDQL - $startTimeDQL) * 1000, 2); // Temps en millisecondes, arrondi à 2 décimales

        // Requête SQL directe pour compter les congés par utilisateur
        $startTimeSQL = microtime(true);
        $connection = $entityManager->getConnection();
        $sql = 'SELECT u.nom, u.prenom, COUNT(c.id) as count 
            FROM conge c 
            JOIN "user" u ON c.user_id = u.id 
            GROUP BY u.nom, u.prenom';

        $stmt = $connection->prepare($sql);
        $congesParUserSQL = $stmt->executeQuery()->fetchAllAssociative();
        $endTimeSQL = microtime(true);
        $executionTimeSQL = round(($endTimeSQL - $startTimeSQL) * 1000, 2); // Temps en millisecondes, arrondi à 2 décimales

        return $this->render('stats/user_stats.html.twig', [
            'congesParUser' => $congesParUser,
            'executionTimeDQL' => $executionTimeDQL . " ms",
            'congesParUserSQL' => $congesParUserSQL,
            'executionTimeSQL' => $executionTimeSQL . " ms",
        ]);
    }
}

src/Controller/UserController.php
<?php
// src/Controller/UserController.php

namespace App\Controller;

use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{

    private $userRepository;

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }


    #[Route('/user', name: 'user')]
    public function List(): Response
    {
       // Utiliser la méthode findAll() pour récupérer tous les utilisateurs
        $users = $this->userRepository->findAll();
       
// Passer les utilisateurs à la vue
        return $this->render('user/index.html.twig', [
          //  'controller_name' => 'UserController',
           'users' => $users,
        ]);
    }
}

templates/base.html.twig
{# templates/base.html.twig #}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Bienvenue!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="icon" href="{{ asset('gestion_Conges_favicon.ico') }}" type="image/x-icon">
        
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ path('app_home') }}">Mon Application</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_home') }}">Accueil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_stats') }}">Statistiques</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_stats_user') }}">Statistiques par utilisateur</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('user') }}">Utilisateurs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('conge') }}">Listes des congés</a>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="container mt-4">
            {% block body %}{% endblock %}
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/conge/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des congés{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Liste des congés</h1>

    {% if userConges is not empty %}
        <div class="card mb-3">
            <div class="card-body p-0">
                <ul class="list-group list-group-flush">
                    {% for conge in userConges %}
                        <li class="list-group-item">
                            <strong>Utilisateur:</strong> {{ conge.user.nom }} {{ conge.user.prenom }}<br>
                            <strong>Type:</strong> {{ conge.type }}<br>
                            <strong>Date de début:</strong> {{ conge.dateDebut|date('d/m/Y') }}<br>
                            <strong>Date de fin:</strong> {{ conge.dateFin|date('d/m/Y') }}<br>
                            <strong>Statut:</strong> {{ conge.statut }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% else %}
        <div class="alert alert-warning text-center" role="alert">
            Aucun congé trouvé.
        </div>
    {% endif %}
</div>
{% endblock %}

templates/home/index.html.twig
{# templates/home/index.html.twig #}
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    <p>Cette page gère les accès aux congés des utilisateurs.</p>
    
    <h2>Liens d'accès</h2>
    <ul>
        <li><a href="{{ path('user') }}">User</a></li>
        <li><a href="{{ path('conge') }}">Conge</a></li>
               
    </ul>
</div>
{% endblock %}

templates/stats/index.html.twig
{# templates/stats/index.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Statistiques des congés{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Statistiques des congés</h1>

    <h2>Total des congés</h2>
    <p>{{ totalConges }}</p>

    <h2>Congés par type (DQL)</h2>
    {% if congesParType is not empty %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Nombre de congés</th>
                </tr>
            </thead>
            <tbody>
                {% for conge in congesParType %}
                    <tr>
                        <td>{{ conge.type }}</td>
                        <td>{{ conge.count }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-warning text-center" role="alert">
            Aucun congé trouvé.
        </div>
    {% endif %}

    <h2>Congés par type (SQL)</h2>
    {% if congesParTypeSQL is not empty %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Nombre de congés</th>
                </tr>
            </thead>
            <tbody>
                {% for conge in congesParTypeSQL %}
                    <tr>
                        <td>{{ conge.type }}</td>
                        <td>{{ conge.count }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-warning text-center" role="alert">
            Aucun congé trouvé.
        </div>
    {% endif %}
</div>
{% endblock %}

templates/stats/user_stats.html.twig
{# templates/stats/user_stats.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Statistiques des congés par utilisateur{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Statistiques des congés par utilisateur (DQL)</h1>

    {% if congesParUser is not empty %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Nombre de congés</th>
                </tr>
            </thead>
            <tbody>
                {% for conge in congesParUser %}
                    <tr>
                        <td>{{ conge.nom }}</td>
                        <td>{{ conge.prenom }}</td>
                        <td>{{ conge.count }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="text-center mt-3">
            <small>Temps d'exécution de la requête DQL : {{ executionTimeDQL }}</small>
        </div>
    {% else %}
        <div class="alert alert-warning text-center" role="alert">
            Aucun congé trouvé.
        </div>
    {% endif %}
</div>

<div class="container mt-5">
    <h1 class="text-center mb-4">Statistiques des congés par utilisateur (SQL)</h1>

    {% if congesParUserSQL is not empty %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Nombre de congés</th>
                </tr>
            </thead>
            <tbody>
                {% for conge in congesParUserSQL %}
                    <tr>
                        <td>{{ conge.nom }}</td>
                        <td>{{ conge.prenom }}</td>
                        <td>{{ conge.count }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="text-center mt-3">
            <small>Temps d'exécution de la requête SQL : {{ executionTimeSQL }}</small>
        </div>
    {% else %}
        <div class="alert alert-warning text-center" role="alert">
            Aucun congé trouvé.
        </div>
    {% endif %}
</div>
{% endblock %}

templates/user/index.html.twig
{# templates/user/index.html.twig #}
{% extends 'base.html.twig' %}

{% block title %}Afficher les utilisateurs{% endblock %}

{% block body %}
<h1>Liste des utilisateurs</h1>

<ul>
    {% for user in users %}
        <li>{{ user.nom }}</li>
    {% else %}
        <li>Aucun utilisateur trouvé.</li>
    {% endfor %}
</ul>

{% endblock %}